[prune]
  go-tests = true

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.8"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/yaml.v1"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.10.0"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "release-1.10"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.10.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.10.0"


[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.1"