[prune]
  go-tests = true

[[constraint]]
  name = "github.com/ghodss/yaml"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "0.11.7"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/go-homedir"

[[constraint]]
  branch = "v1"
  name = "gopkg.in/yaml.v1"

[[constraint]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[constraint]]
  name = "k8s.io/client-go"
  version = "7.0.0"

[[constraint]]
  name = "k8s.io/helm"
  version = "2.9.0"

[[override]]
  name = "github.com/russross/blackfriday"
  version = "1.5.1"